### PR TITLE
Move boolean check in class BungeePlayerListener

### PR DESCRIPTION
**Pull request by nickuc**

### CODE REVIEW

**Comment by sgdc3** [comment]
Any comment?

**Comment by ljacqu** [comment]
Moves an easy check up to avoid performing irrelevant work

**Comment by nickuc** [comment]
> Moves an easy check up to avoid performing irrelevant work

I do not agree. If the following pull request is implemented in the future (https://github.com/AuthMe/AuthMeBungee/pull/48), a useless computational effort will be used, even if the feature is disabled.

**Comment by ljacqu** [comment]
I think you misread my comment ;)

**Comment by nickuc** [comment]
> I think you misread my comment ;)

I read it wrong. I'm sorry.

**Pull request closed without merging**
