### PR TITLE
Simple fixes (config file creation + plugin.yml)

### PR DESCRIPTION
**Pull request by Bodyash**
Fixed config file cannot be created, because plugin folder does not
exist
Fixed maven compiler not including resources (plugin.yml) into target
jars

### CODE REVIEW

**Comment by ljacqu** [comment]
@sgdc3 seems fine to me, minor improvement is that we could check for the result of `mkdirs()` as well.

**Comment by Bodyash** [comment]
@ljacqu Result of mkdirs() , called on parent file of config.yml file - is creating all dirs, if not exist.

**Comment by ljacqu** [comment]
I thought that mkdirs should be checked for its return value but the javadoc says otherwise. I was mistaken

**Comment by sgdc3** [comment]
looks fine

**Review by sgdc3 — APPROVED** [review]

**Pull request merged**
